[package]
name = "bank"
version = "0.1.0"
authors = ["xleyba <xleyba@users.noreply.github.com>"]
edition = "2018"
publish = false

[dependencies]
actix-rt = "0.2"
actix-web = { version="1.0.0-alpha.6" }
actix = "0.8.0"

colored = "1.7"